// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkIyfCUEcrJxD0uMzuWpBv4Gj40KdRxbg',
    appId: '1:722703513140:web:ffa9b8acfee5f1198fbc61',
    messagingSenderId: '722703513140',
    projectId: 'pawscareadoption',
    authDomain: 'pawscareadoption.firebaseapp.com',
    storageBucket: 'pawscareadoption.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkIyfCUEcrJxD0uMzuWpBv4Gj40KdRxbg',
    appId: '1:722703513140:android:5b796ef6406d89068fbc61',
    messagingSenderId: '722703513140',
    projectId: 'pawscareadoption',
    storageBucket: 'pawscareadoption.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIyfCUEcrJxD0uMzuWpBv4Gj40KdRxbg',
    appId: '1:722703513140:ios:ef01b9ed473abe768fbc61',
    messagingSenderId: '722703513140',
    projectId: 'pawscareadoption',
    storageBucket: 'pawscareadoption.appspot.com',
    iosBundleId: 'com.example.pawscare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIyfCUEcrJxD0uMzuWpBv4Gj40KdRxbg',
    appId: '1:722703513140:ios:ef01b9ed473abe768fbc61',
    messagingSenderId: '722703513140',
    projectId: 'pawscareadoption',
    storageBucket: 'pawscareadoption.appspot.com',
    iosBundleId: 'com.example.pawscare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkIyfCUEcrJxD0uMzuWpBv4Gj40KdRxbg',
    appId: '1:722703513140:web:943eecd14236f6e88fbc61',
    messagingSenderId: '722703513140',
    projectId: 'pawscareadoption',
    authDomain: 'pawscareadoption.firebaseapp.com',
    storageBucket: 'pawscareadoption.appspot.com',
  );
} 